**CREATING A NUMPY ARRAY AND ITS ATTRIBUTES**

In [2]:
#Importing numpy
import numpy as np
my_list = [1,3,5,7,9]
my_array = numpy.array(my_list)
print(my_array)
#Creating a numpy array from "my_list"
my_arr = np.array(my_list)
#Printing the array
print(my_arr)

#Creating a 0-D array
arr_0d = np.array(42)
print(arr_0d)

#Creating a 2-D array
arr_2d = np.array([1,2,3,4,5])
print(arr_2d)

#Creating a 3-D aaray
arr_3d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[10,11,12]]])
print(arr_3d)

[1 3 5 7 9]
[1 3 5 7 9]
42
[1 2 3 4 5]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 1  2  3]
  [10 11 12]]]


In [9]:
# Creating array and its attributes

arr = np.array([[1,2,3,4,], [6,7,8,9]])
print(arr) #printing the array
print(arr.shape) #printing the shape of array
print(arr.ndim) #Dimensions
print(arr.dtype) #Types........
print(arr.size) #Size......

SyntaxError: invalid non-printable character U+00A0 (<ipython-input-9-198825bbc78e>, line 8)

In [11]:
#Accesing 1-D array elements
my_arr = np.array([2,5,7,9])
print(my_arr[2])

7


In [13]:
#Accesing 2-D array elementss
my_arr = np.array([[2,5,7,9],[1,3,5,7]])
print(my_arr[1,2])

5


In [15]:
#Accessing 3-D
my_arr = np.array([[[2,5,7,9],[1,3,5,7],[2,5,7,9],[1,3,5,7]]])
print(my_arr[0,1,2])

5


**NEGATIVE INDEXING**

In [18]:
my_arr = np.array([[2,5,7,9],[1,3,5,7]])
print(my_arr[1,-2])

5


**SLICING ARRAYS**

Important concepts while slicing arrays

array[start:end]
array[start:end:step]

In [20]:
#Slicing a 1-D Numpy Array
arr = np.array([1,3,5,7,9,11,13,15,17,19,21])
print(arr[1:5]) #Slicing
print(arr[1:5:2]) #Slicing with step
print(arr[0:-1]) #Slicing with negative index

[3 5 7 9]
[3 7]
[ 1  3  5  7  9 11 13 15 17 19]


In [21]:
#Slicing a 2-D Numpy Array
arr = np.array([[1,3,5,7],[2,4,6,8]])
print(arr[1,1:-1])


[4 6]


#HOMEWORK
-Expirement with slicing on a 3-D Array
#CLASSWORK: Whatsapp group